apiVersion: v1
kind: Service
metadata:
  name: controlplane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: controlplane
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP